name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  govet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run Go vet
        run: make vet

  integration:
    name: Integration Test - ${{ matrix.target }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target:
          - testversion5.6
          - testversion5.7
          - testversion8.0
          - testversion8.4.5
          - testpercona5.7
          - testpercona8.0
          - testmariadb10.3
          - testmariadb10.8
          - testmariadb10.10
          - testtidb6.1.0
          - testtidb7.5.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get -f -y install mysql-client

      - name: Run test
        run: make ${{ matrix.target }}
